name: Publish Package to NPM Registry

on:
  release:
    types: [published]

jobs:
  npm-package:
    runs-on: ubuntu-latest-16-core
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@topos-protocol'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  notification:
    runs-on: ubuntu-latest-16-core
    needs: npm-package
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "repository": "${{ github.repository }}",
              "version": "${{ github.ref }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ vars.RELEASE_PIPELINE_SLACK_WEBHOOK_URL }}
